#!/usr/bin/env bash

set -Eeuo pipefail
[ -z "${DEBUG:-}" ] && DEBUG=0
[ "${DEBUG}" -eq 1 ] && set -x

case "${1}" in
    "--version" | "-v" )
        { printf "$(basename "${0}") v$(cat VERSION)\n"; exit 0; } ;;
    "--help" | "-h" )
        { printf "usage: ./$(basename "${0}") or bash $(basename "${0}")\n"; exit 0; } ;;
esac
